apiVersion: v1
kind: Secret
metadata:
  name: stayhub-secret
  annotations:
    argocd.argoproj.io/hook: Skip
  labels:
    app.kubernetes.io/name: stayhub
    app.kubernetes.io/instance: stayhub
type: Opaque